name: Build and Publish Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Fetch Submodules Recursively
      run: git submodule update --init --recursive

    - name: Generate project
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\generate.bat

    - name: Build t6-mod
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild .\src\client-t6\client-t6.vcxproj /p:Configuration=Release /p:Platform=Win32

    - name: Build iw8-mod
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild .\src\client-iw8\client-iw8.vcxproj /p:Configuration=Release /p:Platform=x64

    - name: Upload t6-mod artifact
      uses: actions/upload-artifact@v4
      with:
        name: t6-mod
        path: build/Win32/Release/t6/d3d11.dll

    - name: Upload iw8-mod artifact
      uses: actions/upload-artifact@v4
      with:
        name: iw8-mod
        path: build/x64/Release/iw8/version.dll